# This file structure matches the Pydantic models in config.py.

project:
  # 'instance' is a required field with no default.
  instance: "Patagonia"
  # You can override default values like the version.
  version: [0, 1, 0] # Corresponds to Tuple[int, int, int]

logging:
  # Set a more verbose logging level for development.
  level: "DEBUG"
  timestamped: true

database:
  # 'name' is a required field within the DatabaseConfig.
  name: "app"

api:
  host: "0.0.0.0"
  port: 8080

message_board:
  enabled: false
  identifier: "hermes_dev"
